/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.bcapp;

import NonFrames.Hasher;
import NonFrames.FileHexConverter;
import NonFrames.FileMetadata;
import static com.mycompany.bcapp.App.multiChainCommand;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import multichain.object.BalanceAsset;
import multichain.object.BalanceAssetBase;
import multichain.object.TransactionWallet;
import multichain.object.TransactionWalletDetailed;
import multichain.object.queryobjects.AssetParams;
import multichain.object.queryobjects.CustomParamString;
/**
 *
 * @author xavyr
 */
public class SendAssetWithFileFrame extends javax.swing.JFrame {

    /**
     * Creates new form SendAssetWithFileFrame
     */
    private String hash;
    private String fileName;
    private String path;
    private String sender;
    
    
    public SendAssetWithFileFrame() {
        initComponents();
        this.setSize(640, 480);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
ImageIcon ic = new ImageIcon("C:\\Users\\xavyr\\Documents\\NetBeansProjects\\bcApp\\bcApp\\src\\main\\java\\com\\mycompany\\bcapp\\icon.png");
        this.setIconImage(ic.getImage());
        CustomParamString x = new CustomParamString();
        BalanceAssetBase v = new BalanceAssetBase();
        v.setName("test");
        v.setQty(1);
        List<BalanceAssetBase> ab = new ArrayList<>();
        ab.add(v);
        sender = App.address;
        
        System.out.println("success");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        sendAssetWithFileButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        assetNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        filePathField = new javax.swing.JTextField();
        uploadButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Send asset with file");

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        sendAssetWithFileButton.setText("Send asset with file");
        sendAssetWithFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendAssetWithFileButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Asset name:");

        jLabel2.setText("File:");

        uploadButton.setText("Select");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sendAssetWithFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addComponent(closeButton)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(filePathField, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assetNameField))
                        .addGap(26, 26, 26)
                        .addComponent(uploadButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assetNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(sendAssetWithFileButton))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
         JFileChooser fileChooser = new JFileChooser();
        FileHexConverter fhc = new FileHexConverter();
        int returnVal = fileChooser.showOpenDialog(fileChooser);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            filePathField.setText(file.getPath());
            fileName = file.getName();
            try{
             hash = Hasher.getMD5Checksum(file);
            } catch(Exception e){
                e.printStackTrace();
            }            
        }
    }//GEN-LAST:event_uploadButtonActionPerformed

    private void sendAssetWithFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendAssetWithFileButtonActionPerformed
        String assetName = assetNameField.getText();
        String path = "C:\\" + fileName;
        
        FileMetadata fmd = new FileMetadata();
        fmd.hash = hash;
        fmd.location = path;
        fmd.sender = this.sender;
        fmd.assetName = assetName;
        
        BalanceAssetBase b = new BalanceAssetBase();
 
        b.setName(assetName);
        b.setQty(0.1);
 
        List<BalanceAssetBase> bs = new ArrayList<>();
        bs.add(b);
        FileHexConverter fhx = new FileHexConverter();
        String hex = fhx.stringToHex(fmd.toJson());
        String to = "1JqNi2Fhp9QK4HQsj1DzENzW2NFFR4fE2uHUYt";
        
        try{
            App.multiChainCommand.getWalletTransactionCommand().SendWithMetaData(to, bs, hex);
        }catch(Exception e){
            e.printStackTrace();
        }
                this.dispose();        // TODO add your handling code here:

    }//GEN-LAST:event_sendAssetWithFileButtonActionPerformed

    
    private String fileExtension(String path){
        String file = path.substring(path.lastIndexOf("\\"));
        String ext = file.substring(file.indexOf("."));
        
        return ext;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendAssetWithFileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendAssetWithFileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendAssetWithFileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendAssetWithFileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendAssetWithFileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assetNameField;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField filePathField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton sendAssetWithFileButton;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables
}
